version: '3.9'

services:
    whisper:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${WHISPER_PORT:-5001}:5001'
        volumes:
            - ./models:/app/models
        restart: unless-stopped
